package com.example.handlingformsubmission;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

@Entity
public class Feedback {
    @Id
    private long id;

	private String name; // Optional if doing bug report, or Provider does not display Name publicly for reviews
	private String email; // optional
	private String feedback;
	private String content;
	private boolean isBugReport;

// NOTE: Class will work without constructors, but setters are required
	public Feedback() {}
	public Feedback(long id, String name, String email, String feedback, boolean isBugReport, String content) {
//		this.id = id; // ID automatically generated by Database
		this.name = name;
		this.email = email;
		this.feedback = feedback;
		this.isBugReport = isBugReport;
		this.content = content;
	}

//	public void setId(long id) { this.id = id; } // we will need to retrieve a generated ID from Database microservice
	public long getId() {
		return id;
	}

	public void setName(String name)  { this.name = name; }
	public void setEmail(String email) { this.email = email; }
	public void setContent(String content) { this.content = content; }
	public void setIsBugReport(boolean isBugReport) { this.isBugReport = isBugReport; }

	public String getName() { return name; }
	public String getEmail() { return email; }
	public String getContent() { return content; }
	public boolean getIsBugReport() { return isBugReport; }
}
