package com.example.handlingformsubmission;

import jakarta.persistence.Entity;
import jakarta.persistence.Id;

//* Feedback Model Class

@Entity
public class Feedback {
    @Id
    private long id;

	private String name = ""; // Optional if doing bug report, or Provider does not display Name publicly for reviews
	private String email = ""; // optional
	private String content;
	private boolean isBugReport;

	public Feedback() {}
	public Feedback(String name, String email, String content, boolean isBugReport) {
		// ID automatically generated by Database, and we access it from the database
		this.name = name;
		this.email = email;
		this.content = content;
		this.isBugReport = isBugReport;
	}

	public void setId(long id) {this.id = id;} // we retrieve a generated ID from Database microservice
	public long getId() {
		return id;
	}

	public void setName(String name)  { this.name = name; }
	public void setEmail(String email) { this.email = email; }
	public void setContent(String content) { this.content = content; }
	public void setIsBugReport(boolean isBugReport) { this.isBugReport = isBugReport; }

	public String getName() { return name; }
	public String getEmail() { return email; }
	public String getContent() { return content; }
	public boolean getIsBugReport() { return isBugReport; }
}
